### PR TITLE
Taking a swag at #104

### PR DESCRIPTION
**Pull request by sheeley**
I thought #104 is a pretty solid idea. I'm not really much of an Objective C/macOS developer, so whipped up a bit of a draft to see if this is the right direction to head. Feel free to jump all over it and let me know where it could be better/if this is the right path to take.

### CODE REVIEW

**Comment by newmarcel** [comment]
Cool 😎! Sorry for the delayed response, I had to take a break from the project after the 1.5.0 release.

Do you maybe mean #108 instead? Either way, the approach seems to be working for me, the distributed notification center notifications arrive when locked.

So feel free to continue down this path 😃 I will gladly merge this when you feel ready.

The only note I have would be to place this in the advanced preferences… _(e.g. I also use KYA when the screen is locked (after I trigger my screen saver manually))_. But this is just a minor storyboard detail.

Many thanks for your contribution!

**Comment by sheeley** [comment]
Yup, #108 is correct! I'll take a look at continuing, but am currently struggling with getting it to actually build locally - as someone utterly ignorant of fastlane, should I read their docs, or is there stuff specific to KYA I should know? 

The issue I'm running into is:
```
Showing All Messages
:-1: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "5KE..." with a private key was found. (in target 'KeepingYouAwake Launcher')
```

**Comment by sheeley** [comment]
@newmarcel are there any instructions/scripts/commands I should take a look at? I do actually want to build this, Cocoa's just not my strength. Yet. :)

**Comment by newmarcel** [comment]
I'm closing this PR because there hasn't been any recent activity.

**Comment by Hildebrand-Ritense** [comment]
such a pity this never got merged. Would there be a chance this could be integrated nonetheless, maybe @newmarcel pick up where sheeley left?

**Pull request closed without merging**
