### PR TITLE
Translation into French [Cleaned Up]

### PR DESCRIPTION
**Pull request by newmarcel**
This is the cleaned up version of #51 for merging.

### CODE REVIEW

**Comment by rei-vilo** [comment]
Seems ok. Thanks!

**Comment by rei-vilo** [comment]
The translation for the **Preferences** pane seem to have been lost!

capture 2016-10-14 a 22 42 50

**Comment by rei-vilo** [comment]
However, the project does include the translation.

capture 2016-10-14 a 22 44 52

**Comment by newmarcel** [comment]
Strange, have you checked out the updated `master`? It looks like this for me:

prefs

**Comment by rei-vilo** [comment]
Yes, I've pulled the updated code with pull request 52.

I've tried again. I've deleted the GitHub folder on my MacBook, downloaded again and compiled again. Same result.

**Comment by rei-vilo** [comment]
However, I obtain the correct translation (everything on French) if I download the [ZIP file](https://github.com/newmarcel/KeepingYouAwake/archive/master.zip) and compile it.

**Pull request merged**
