### PR TITLE
Translation into French

### PR DESCRIPTION
**Pull request by rei-vilo**
Two exception for translated text. French not taken into account for 1-
names of the panes for Preferences, 2- pull-down menu.

### CODE REVIEW

**Comment by alexandreleroux** [comment]
Thanks @rei-vilo :-) I'll have a few minor improvements to this French translation (both MainMenu.strings and Preferences.strings) once it is (hopefully) approved by @newmarcel . Thanks for getting the ball rolling for KYA translations! -- Alex

**Comment by alexandreleroux** [comment]
This pull request from @rei-vilo is related to issue #20

**Comment by rei-vilo** [comment]
You're welcome! I like this utility, and it's always better in mother's tongue.

Other strings are available in `Preferences.strings` line 99 _sq._

They don't seem to be taken into account.

Feel free to improve the translation.

**Comment by rei-vilo** [comment]
@alexandreleroux

No news since my pull request.

Feel free to review the French translation at https://github.com/rei-vilo/KeepingYouAwake

**Comment by alexandreleroux** [comment]
@rei-vilo done, I made modifications to your fork. The next step would be to update this pull request? Regards! -- Alex

**Comment by newmarcel** [comment]
Hi there. Sorry for the very long delay in regard to localizations.

I have now updated the master branch with various improvements that allow better localizability. I also added `German` as an official translation and template for all other localizations.

It would be great if you could sync with the current master and also provide an XLIFF file (generated by Xcode 8).

In regard to the credits: I don't want them to be translated (yet), but feel free to add yourself as Contributor 😃

**Comment by rei-vilo** [comment]
Thank for you answer. There are 2 problems:

1. This branch has conflicts that must be resolved
2. I don't have Xcode 8 installed yet.

**Comment by newmarcel** [comment]
Ok, no problem. Let's walk through the process. I've tested it with Xcode 7 and it's still compatible.

The best approach to migrate your translation might be through the XLIFF files (see master: Localizations folder). Xcode packages up the localizations and exports them as easy-to-process XML.

1) If you select the project file in the sidebar and click "Editor" > "Export For Localization…" in the menu you should get a nice XLIFF export for "French".

2) You can then switch to the current master branch and use the same menu to "Import Localizations…". 

3) Some strings might have changed so ideally you would then export AGAIN and make sure the fr.xliff is up-to-date. You can then put that in the Localizations folder and re-import one last time to sync everything up.

4) make a commit 😄 

To get this PR clean you could reset it back to the master branch state and make your commit.

`git reset --hard origin/master` might be of help _(be careful if you've never done this before!)_ or alternatively closing and re-opening would be another option.

Btw, I use [Xliffie](http://hotmilktea.com/xliffie/) from the Mac App Store to work with XLIFF files, but it crashes a lot.

**Comment by rei-vilo** [comment]
French translations with `fr.xliff`

* Still an issue on the **Preferences** window and panes not translated (hard-coded?)

capture 2016-08-21 a 16 37 34

**Comment by newmarcel** [comment]
That's a bug I fixed for the `de` translation already and shouldn't appear in this branch. Also this PR somehow contains now a whole lot of changes which are already in master (that's why it's not mergable).

Can you try to import your `fr.xliff` file into a clean checkout of the current master branch? There the problem shouldn't appear.

**Comment by rei-vilo** [comment]
French translations with fr.xliff
Preference window issue fixed now

**Comment by newmarcel** [comment]
Hi @rei-vilo, in order to get this merged, I need a cleaned up pull request. I therefore took the changes of your PR here and created a new one with just the required changes.

If you approve of this. I will merge this new PR and close this one.

**New PR:** #62

**Comment by rei-vilo** [comment]
Thank you for your answer. I don't understand how my pull request has conflicts now, as it was ok when I created it. Anyway, I'll take a look at #62.

**Pull request closed without merging**
