### PR TITLE
Add display sleep support

### PR DESCRIPTION
**Pull request by creamelectricart**
Here's my attempt to add display sleep support.

I am not experienced in this at all, so apologies if there are obvious mistakes.

Basically I've tried to implement a preference that uses caffeinate with the '-i' argument to allow display sleep while keeping the machine awake.

thanks, hope this helps.
Tristan.

#138 #115 #25 #12

### CODE REVIEW

**Comment by agret** [comment]
Great idea. I'd love if you could add a menu item to immediately sleep the display when clicked too, sometimes have to leave things copying and don't want any burn-in to occur on the display.

**Comment by ahydronous** [comment]
@newmarcel any chance of taking a peek at this pull request?

**Comment by newmarcel** [comment]
Merged. Thank you for your contribution 👍 and sorry for the delayed response

**Comment by basnijholt** [comment]
Great feature!

After how long will the display "go to sleep"?

**Comment by creamelectricart** [comment]
> Great feature!
> 
> After how long will the display "go to sleep"?

How long depends upon what you have set in the System Preferences under 'Energy Saver'.

**Comment by basnijholt** [comment]
Great! That's what I expected 😄

**Comment by basnijholt** [comment]
Great! That's what I expected 😄 

Do you know if any of these other settings interfere:
image

**Comment by creamelectricart** [comment]
> Great! That's what I expected 😄
> 
> Do you know if any of these other settings interfere:

I don't believe so but I'm not sure. That's more of a macOS thing than a KeepingYouAwake thing I think!

**Pull request merged**
